version: '3.8'

services:
  bot:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=telegram-bot-api-integration{POSTGRES_USER}
      - POSTGRES_PASSWORD=telegram-bot-api-integration{POSTGRES_PASSWORD}
      - POSTGRES_DB=telegram-bot-api-integration{POSTGRES_DB}
    volumes:
      - .:/app
    command: python -m src.webhook

  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=telegram-bot-api-integration{POSTGRES_USER}
      - POSTGRES_PASSWORD=telegram-bot-api-integration{POSTGRES_PASSWORD}
      - POSTGRES_DB=telegram-bot-api-integration{POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - bot

volumes:
  postgres_data:
